#!/usr/bin/env node
// AI-assisted draft summary for release notes / PRs.
//
// Usage:
//   node scripts/release-summary.mjs <from-ref> <to-ref>
//   node scripts/release-summary.mjs <to-ref>
//
// Reads conventional commits (`type(scope): subject`) over the given git range
// and emits a grouped, human-draftable markdown summary for release notes or a
// PR body. Runs inside repositories with git available (e.g. the
// release-on-tag workflow, which checks out with full history).
//
// Honesty contract: this is a DRAFT, not a metric. It is guidance an author
// reviews before publishing — it never feeds delivery telemetry (ADR 0008's
// "never invent" ethos applies to numbers, not to a first-pass writeup).

import { execSync } from 'node:child_process';

const [, , a, b] = process.argv;
const [fromRef, toRef] = b !== undefined ? [a, b] : [undefined, a];

const range = fromRef
  ? `${fromRef}..${toRef || 'HEAD'}`
  : toRef || 'HEAD';

let commits = [];
try {
  const out = execSync(`git log --format=%s ${range}`, {
    maxBuffer: 10 * 1024 * 1024,
    stdio: ['ignore', 'pipe', 'ignore'],
  })
    .toString()
    .trim();
  commits = out ? out.split('\n') : [];
} catch {
  commits = [];
}

if (commits.length === 0 && !fromRef) {
  try {
    const out = execSync('git log --format=%s -20 HEAD', {
      maxBuffer: 10 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
    commits = out ? out.split('\n') : [];
  } catch {
    commits = [];
  }
}

const CONVENTIONAL = /^([a-z]+)(?:\(([^)]+)\))?!?:\s+(.+)$/;
const groups = { features: [], fixes: [], documentation: [], maintenance: [], other: [] };

for (const line of commits) {
  const match = CONVENTIONAL.exec(line);
  if (!match) {
    groups.other.push(line);
    continue;
  }
  const [, type, scope, subject] = match;
  const entry = scope ? `${subject} (\`${scope}\`)` : subject;
  if (type === 'feat' || type === 'feature') groups.features.push(entry);
  else if (type === 'fix' || type === 'bugfix') groups.fixes.push(entry);
  else if (type === 'docs' || type === 'doc') groups.documentation.push(entry);
  else if (
    ['chore', 'ci', 'build', 'refactor', 'test', 'perf', 'style'].includes(type)
  ) {
    groups.maintenance.push(entry);
  } else {
    groups.other.push(entry);
  }
}

const total = commits.length;
const typeCounts = Object.entries(groups)
  .filter(([, items]) => items.length > 0)
  .map(([name, items]) => `${name} ${items.length}`)
  .join(', ');

const sections = [
  '## AI-assisted draft summary',
  '',
  '_Draft generated by `scripts/release-summary.mjs` — review and edit before publishing. A draft is guidance, not a delivery metric (ADR 0008 ethos)._',
  `- **Commits scanned**: ${total}`,
  `- **Type mix**: ${typeCounts || 'none'}`,
  '',
];

const HEADINGS = {
  features: '### Features',
  fixes: '### Fixes',
  documentation: '### Documentation',
  maintenance: '### Maintenance',
  other: '### Other',
};

for (const section of ['features', 'fixes', 'documentation', 'maintenance', 'other']) {
  const items = groups[section];
  if (items.length === 0) continue;
  sections.push(HEADINGS[section]);
  sections.push(...items.map((entry) => `- ${entry}`), '');
}

if (commits.length === 0) {
  sections.push('_No commit subjects parsed for this range — add notes by hand._', '');
}

process.stdout.write(sections.join('\n'));