#!/usr/bin/env node
// Headless release-train simulation run mode.
//
// Usage: node --experimental-strip-types scripts/release-train-simulator.mts [output-dir]
//
// Runs the deterministic Phase 11 model (frontend/src/lib/release-train.ts)
// and writes a clearly-labeled simulation report. A configuration may be
// supplied via the SIM_CONFIG environment variable as JSON; otherwise a
// default configuration is used. Every output self-identifies as simulation
// and the script never creates deployments, releases, PRs, or issues — the
// report files are its only output, so delivery-telemetry stays truthful.

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";
import { simulateReleaseTrain, type ReleaseTrainConfig } from "../frontend/src/lib/release-train.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));

const outputDir = resolve(process.argv[2] ?? ".github/pdm/reports");

const defaultConfig: ReleaseTrainConfig = {
  trainIntervalDays: 14,
  capacity: 3,
  gatePassRate: 1,
  slipPolicy: "carry",
  seed: 42,
  maxTrains: 10,
  backlog: [
    { id: "feat-a", size: 2, readiness: 1 },
    { id: "feat-b", size: 3, readiness: 1 },
    { id: "feat-c", size: 1, readiness: 1 },
  ],
};

function loadConfig(): ReleaseTrainConfig {
  if (!process.env.SIM_CONFIG) {
    return defaultConfig;
  }
  const parsed = JSON.parse(process.env.SIM_CONFIG) as Partial<ReleaseTrainConfig>;
  return { ...defaultConfig, ...parsed };
}

const config = loadConfig();
const result = simulateReleaseTrain(config);

if (!existsSync(outputDir)) {
  mkdirSync(outputDir, { recursive: true });
}

const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
const reportPath = join(outputDir, `release-train-simulation-${timestamp}.json`);
const markdownPath = join(outputDir, `release-train-simulation-${timestamp}.md`);

const report = {
  kind: "simulation",
  generated_at: timestamp,
  config,
  result,
};

writeFileSync(reportPath, JSON.stringify(report, null, 2) + "\n");

const markdown = [
  "## Release train simulation (headless)",
  "",
  "_This is a labeled simulation report. It is NOT a delivery record and does not feed delivery-telemetry metrics._",
  "",
  `- **Seed**: \`${config.seed}\``,
  `- **Train interval**: ${config.trainIntervalDays} days`,
  `- **Capacity**: ${config.capacity} feature(s) per train`,
  `- **Gate pass rate**: ${Math.round(config.gatePassRate * 100)}%`,
  `- **Slip policy**: \`${config.slipPolicy}\``,
  "",
  "### Outcomes",
  "",
  `- **Throughput**: ${(result.throughput * 100).toFixed(1)}%`,
  `- **On-time rate**: ${(result.onTimeRate * 100).toFixed(1)}%`,
  `- **Average delay**: ${result.averageDelayTrains.toFixed(1)} trains`,
  "",
  "### Train schedule",
  "",
  ...(result.trains.length === 0
    ? ["_No features boarded._", ""]
    : result.trains.map(
        (train) =>
          `- **Train ${train.train}** (${train.features.length}): ${train.features.join(", ")}`,
      )),
  "",
  "_Generated by `scripts/release-train-simulator.mts` — outputs carry `kind: \"simulation\"` and are never merged into GitHub-native delivery records (ADR 0010)._",
  "",
].join("\n");

writeFileSync(markdownPath, markdown + "\n");
console.log(`wrote ${reportPath}`);
console.log(`wrote ${markdownPath}`);
console.log(`kind=simulation`);
