#!/usr/bin/env node
// Offline, deterministic diff risk-review heuristic with an AI hook point.
//
// Usage: node scripts/risk-review.mjs <input-json> <output-md>
//
// The input JSON is written by risk-health-check: { base, head, numstat } where
// `numstat` is the base64-encoded output of `git diff --numstat <base>..<head>`.
// When the environment variable AI_REVIEW_CMD is set it is invoked with the
// input path as its first argument (future AI agent-runner integration point);
// otherwise the built-in heuristics below are used. Results are surfaced as
// `risk_score=<n>` and `risk_summary=<text>` on stdout so the workflow can copy
// them into $GITHUB_OUTPUT.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';

const [, , inputPath, outputPath] = process.argv;

if (!inputPath || !outputPath || !existsSync(inputPath)) {
  console.error('usage: node scripts/risk-review.mjs <input-json> <output-md>');
  process.exit(2);
}

const payload = JSON.parse(readFileSync(inputPath, 'utf8'));

const aiCmd = process.env.AI_REVIEW_CMD;
if (aiCmd) {
  execSync(`${aiCmd} ${inputPath}`, { shell: true, stdio: 'inherit' });
}

const numstatText = Buffer.from(payload.numstat || '', 'base64')
  .toString('utf8')
  .trim();

const rows = numstatText
  .split('\n')
  .filter(Boolean)
  .map((line) => {
    const [added, deleted, ...pathParts] = line.split('\t');
    return {
      filePath: pathParts.join('\t'),
      added: added === '-' ? 0 : Number(added) || 0,
      deleted: deleted === '-' ? 0 : Number(deleted) || 0,
    };
  });

const totalFiles = rows.length;
const totalAdded = rows.reduce((sum, r) => sum + r.added, 0);
const totalDeleted = rows.reduce((sum, r) => sum + r.deleted, 0);
const totalChanges = totalAdded + totalDeleted;

const sensitivePattern = /(secret|token|password|credential|api[_-]?key|\.env\b|id_rsa|\.pem|auth)/i;
const sensitiveFiles = rows.filter((r) => sensitivePattern.test(r.filePath)).length;
const oversizedFiles = rows.filter((r) => r.added > 500).length;

let score = 0;
let reasons = [];

if (totalFiles <= 0) {
  score = 0;
  reasons.push('no file changes parsed');
} else {
  if (totalChanges < 20) {
    score = 1;
    reasons.push('small diff');
  } else if (totalChanges < 100) {
    score = 3;
    reasons.push('moderate diff size');
  } else if (totalChanges < 500) {
    score = 5;
    reasons.push('large diff size');
  } else {
    score = 7;
    reasons.push('very large diff size');
  }
  if (sensitiveFiles > 0) {
    score = Math.min(10, score + 3);
    reasons.push(`${sensitiveFiles} sensitive-path file(s) touched`);
  }
  if (oversizedFiles > 0) {
    score = Math.min(10, score + 1);
    reasons.push(`${oversizedFiles} file(s) exceed 500 added lines`);
  }
  if (totalDeleted > totalAdded) {
    score = Math.min(10, score + 1);
    reasons.push('deletions outnumber additions');
  }
}

const label = score <= 2 ? 'low' : score <= 5 ? 'medium' : 'high';
const summary =
  `${label} risk: ${totalFiles} file(s), +${totalAdded}/-${totalDeleted} lines. ` +
  reasons.join('; ') + (aiCmd ? '. AI review hook invoked (AI_REVIEW_CMD).' : '.');
const meta = payload.base === '4b825dc642cb6eb9a060e54bf8d69288fbee4904'
  ? '_Full-tree baseline: base is the empty-tree hash (no PR context), so the diff covers the whole first commit._'
  : '';

const md = [
  '## Diff risk review',
  '',
  `- **Risk score**: ${score}/10 (${label})`,
  `- **Scope**: ${totalFiles} file(s), +${totalAdded}/-${totalDeleted} lines`,
  `- **Heuristics**: ${reasons.join('; ') || 'none'}`,
  `- **Diff**: base \`${payload.base?.slice(0, 7)}\` → head \`${payload.head?.slice(0, 7)}\``,
  meta ? `- ${meta}` : null,
  '',
  '_Generated by `scripts/risk-review.mjs` — offline heuristics with an AI hook point via `AI_REVIEW_CMD`._',
  '',
].filter((l) => l !== null).join('\n');

writeFileSync(outputPath, md + '\n');
console.log(`risk_score=${score}`);
console.log(`risk_summary=${summary}`);